config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  get 'donations/new'
  get 'donations/create'
  # root 'articles#index'
  get 'up' => 'rails/health#show', as: :rails_health_check

  root 'categories#index'
  resources :categories do
    resources :articles do
      resources :comments
    end
  end
  resources :donations, only: %i[new create]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  include Visible

  has_many :comments, dependent: :destroy
  belongs_to :category

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
  validates :category, presence: true

  def self.last_five
    all.last(5)
  end 
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :articles

  validates :name, presence: true, uniqueness: true

  def article_count
    articles.count
  end
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  include Visible

  belongs_to :article
  
  end

app/models/concerns/visible.rb
# frozen_string_literal: true

module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = %w[public private archived].freeze

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/models/donation.rb
# frozen_string_literal: true

class Donation < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  validates :first_name, :last_name, :username, presence: true

  def user_comments
    comments
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name username])
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_category
  before_action :set_article, only: %i[show edit update destroy]
  def index
    @articles = Article.all
  end

  def index
    @articles = @category.articles
  end

  def show
    # @article = Article.find(params[:id])
  end

  def new
    # @article = Article.new
    @article = @category.articles.build
  end

  def create
    # @article = Article.new(article_params)

    # if @article.save
    #   redirect_to @article
    # else
    #   render :new, status: :unprocessable_entity
    # end
    @article = @category.articles.build(article_params)
    if @article.save
      redirect_to category_article_path(@category, @article), notice: 'Article was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    # @article = Article.find(params[:id])
  end

  def update
    # @article = Article.find(params[:id])

    # if @article.update(article_params)
    #   redirect_to @article
    # else
    #   render :edit, status: :unprocessable_entity
    # end
    # @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to category_article_path(@category, @article), notice: 'Article was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    # @article = Article.find(params[:id])
    redirect_to root_path, status: :see_other

    @article.destroy
    redirect_to category_articles_path(@category), notice: 'Article was successfully destroyed.'
  end

  private

  def set_category
    @category = Category.find(params[:category_id])
  end

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :body, :status)
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show destroy]
  before_action :authenticate_user!, except: %i[index show]

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(categories_params)

    if @category.save
      redirect_to category_path(@category), notice: 'Category was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @category.update(categories_params)
      redirect_to root_path, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    redirect_to root_path, notice: 'Article was successfully destroyed.'
    @category.destroy
  end

  private

  def set_category; end

  def categories_params
    params.require(:category).permit(:name, :description)
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :authenticate_user!, only: :destroy

  def index
    @comments = Comment.where(article_id: params[:article_id])
    render json: @comments
  end

  def create
    @category = Category.find(params[:category_id])
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to category_article_path(@category, @article)
  end

  def destroy
    @category = Category.find(params[:category_id])
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to category_article_path(@category, @article), status: :see_other
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body, :status)
  end
end

app/controllers/donations_controller.rb
# frozen_string_literal: true

class DonationsController < ApplicationController
  require 'stripe'

  def new
    @donation = Donation.new
  end

  def create
    @donation = Donation.new(donation_params)

    # Charge the user's card
    Stripe::Charge.create({
                            amount: @donation.amount * 100, # convert to cents
                            currency: 'usd',
                            source: params[:stripe_token],
                            description: 'Donation'
                          })

    @donation.save

    flash[:success] = 'Thank you for your donation!'
    redirect_to root_path
  rescue Stripe::CardError => e
    flash[:error] = e.message
    render :new
  end

  private

  def donation_params
    params.require(:donation).permit(:first_name, :last_name, :email, :amount)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

module ArticlesHelper
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/donations_helper.rb
# frozen_string_literal: true

module DonationsHelper
end

app/views/articles/_form.html.erb
<head> <%= stylesheet_link_tag 'style' %>
</head>

<%= form_with model: [@category, @article] do |form| %>
    <div>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
      <% article.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :body %><br>
      <%= form.text_area :body %><br>
      <% article.errors.full_messages_for(:body).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
        <%= form.label :status %><br>
        <%= form.select :status, Visible::VALID_STATUSES, selected: article.status || 'public' %>
    </div>

    <div class="field">
      <%= form.label :category_id %><br>
      <%= form.collection_select :category_id, Category.all, :id, :name, prompt: 'Select a category' %>
    </div>


    <div>
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/articles/edit.html.erb
<head> <%= stylesheet_link_tag 'style' %>
</head>

<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<head> <%= stylesheet_link_tag 'style' %>
</head>

<h1>Articles</h1>

Our blog has <%= Article.public_count %> articles and counting!

<ul>
  <% @articles.each do |article| %>
    <% unless article.archived? %>
       <li>
        <%= link_to article.title, category_article_path(article.category, article) %>
      </li>
    <% end %>
  <% end %>
</ul>

<%= link_to "New Article", new_category_article_path(@category) %>

app/views/articles/new.html.erb
<head> <%= stylesheet_link_tag 'style' %>
</head>

<h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<div class= "articleContent"  style="border: gray solid 2px ">

  <p><%= @article.body %></p>
  <p><strong>Category:</strong> <%= @article.category.name %></p>

  <ul>
    <li><%= link_to "Edit", edit_category_article_path(@category, @article) %></li>
    <li><%= link_to "Delete", category_article_path(@category), data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
    } %></li>
  </ul>
</div>

<button class= "toggleContent" style="background-color: #4CAF50; border: none;color: white;
padding: 10px 32px;
border-radius: 5px;
font-size: 16px;
margin: 4px 2px;">Toggle Article Info</button>

app/views/categories/_form.html.erb
<head> <%= stylesheet_link_tag 'style' %>
</head>

<%= form_with model: @category do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% @category.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %><br>
    <% @category.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<head> <%= stylesheet_link_tag 'style' %>
</head>

<h1>Edit Article</h1>

<%= render "form", category: @category %>

app/views/categories/index.html.erb
<head> <%= stylesheet_link_tag 'style' %>
</head>
<% if user_signed_in?%>
  <div> 👋🏻 
    Welcome, <%= current_user.username%>! </div>
  <%=button_to "Sign out", destroy_user_session_path, method: :delete%>
<ul>
  <% @categories.each do |category| %>
    <li class = "container"><strong><%= link_to category.name, category_path(category) %></strong>:
    <% count = category.article_count %>
    <%= "#{count} #{count == 1 ? 'article' : 'articles'}" %>
    <br> <em> <%= category.description %> </em></li>
  <% end %>
</ul>
<%= link_to "New Category", new_category_path(@category) %>
<% else %>
  <%= button_to "Sign in", new_user_session_path%>
  <ul>
  <% @categories.each do |category| %>
    <li class = "container"><strong><%= link_to category.name, category_path(category) %></strong>:
    <% count = category.article_count %>
    <%= "#{count} #{count == 1 ? 'article' : 'articles'}" %>
    <br> <em> <%= category.description %> </em></li>
  <% end %>
</ul>
<% end %>

app/views/categories/new.html.erb
<head> <%= stylesheet_link_tag 'style' %>
</head>

<h1>New category</h1>

<%= render "form", category: @category %>

app/views/categories/show.html.erb
<head> <%= stylesheet_link_tag 'style' %>
</head>
<h1><%= @category.name %></h1>
<p><%= @category.description %></p>
<ul>
<li><%= link_to "Articles", category_articles_path(@category, @articles) %></li>
  <li><%= link_to "Edit", edit_category_path(@category) %></li>
  <li><%= link_to "Delete", category_path(@category), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
  } %></li>
</ul>

<%= link_to 'Create Article', new_category_article_path(@category) %>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
  <br/>
  <button class="like-button">Like</button>
  <p>
        <%= link_to "Delete Comment", category_article_comment_path(@category, @article, comment), data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
      } %>
  </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @category, @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body, id: 'comment-body' %>
  </p>
  
  <p>
  <%= form.label :status %><br>
  <%= form.select :status, Visible::VALID_STATUSES, selected: 'public' %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/donations/create.html.erb
<h1>Donations#create</h1>
<p>Find me in app/views/donations/create.html.erb</p>

app/views/donations/new.html.erb
<head>
  <%= stylesheet_link_tag 'donation' %>
</head>

<h1>Make a Donation</h1>
<%= form_with(model: @donation, url: donations_path,
method: 'post', local: true, id: 'donation-form') do |form| %>
    <div class="field">
        <%= form.label :first_name %>
        <%= form.text_area :first_name %>
    </div>
    <div class="field">
        <%= form.label :last_name %>
        <%= form.text_area :last_name %>
    </div>
    <div class="field">
        <%= form.label :email %>
        <%= form.text_area :email %>
    </div>
    <div class="field">
        <%= form.label :amount %>
        <%= form.text_area :amount %>
    </div>
    <div id="card-container">
    <div id = "card-element" class = "form-control">
    </div>
    <div id="card-errors" role="alert"></div>
    <button id="donate-button" class ="btn btn-primary">Donate</button>
    </div>
    <%end  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag 'https://js.stripe.com/v3/' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>